import { Controller,Get,Patch,Post,Body,Param,Req,UseGuards,BadRequestException } from '@nestjs/common';
import { IsIn,IsString,MinLength } from 'class-validator';
import { SessionGuard,Roles,AuthRequest } from '../common/session.guard';
import { PrismaService } from '../prisma/prisma.service';
import { CategoryDto,PlanDto,RefundDto } from './dto';
class ResolveDto {@IsIn(['COMPLETED','CANCELLED']) status!:'COMPLETED'|'CANCELLED';@IsString() @MinLength(10) reason!:string;}
@Roles('ADMIN') @UseGuards(SessionGuard) @Controller('admin') export class AdminController {
 constructor(private db:PrismaService){}
 @Get() async overview(){return {users:await this.db.user.findMany({select:{id:true,name:true,email:true,roles:true,deletedAt:true},take:100,orderBy:{createdAt:'desc'}}),creators:await this.db.creator.findMany({include:{user:{select:{name:true}}},take:100}),bookings:await this.db.booking.findMany({include:{request:true},take:100,orderBy:{createdAt:'desc'}}),disputes:await this.db.dispute.findMany({where:{status:'OPEN'},take:100}),support:await this.db.supportTicket.findMany({take:100}),payments:await this.db.paymentTransaction.findMany({take:100,orderBy:{createdAt:'desc'}}),plans:await this.db.subscriptionPlan.findMany(),categories:await this.db.category.findMany(),audit:await this.db.auditLog.findMany({take:50,orderBy:{createdAt:'desc'}})};}
 @Patch('creators/:id/verify') async verify(@Req() r:AuthRequest,@Param('id') id:string){return this.db.$transaction(async tx=>{await tx.auditLog.create({data:{actorId:r.authUser!.id,action:'VERIFY_CREATOR',entity:'Creator',entityId:id}});return tx.creator.update({where:{id},data:{verifiedAt:new Date()}});});}
 @Post('categories') async category(@Req() r:AuthRequest,@Body() d:CategoryDto){return this.db.$transaction(async tx=>{await tx.auditLog.create({data:{actorId:r.authUser!.id,action:'UPSERT_CATEGORY',entity:'Category',entityId:d.slug}});return tx.category.upsert({where:{slug:d.slug},create:d,update:d});});}
 @Patch('plans/:id') async plan(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:PlanDto){return this.db.$transaction(async tx=>{await tx.auditLog.create({data:{actorId:r.authUser!.id,action:'UPDATE_PLAN',entity:'SubscriptionPlan',entityId:id}});return tx.subscriptionPlan.update({where:{id},data:{...d,priceMinor:BigInt(d.priceMinor)}});});}
 @Post('payments/:id/sandbox-refund') async refund(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:RefundDto){if(process.env.PAYMENTS_MODE!=='sandbox')throw new BadRequestException('Sandbox disabled');return this.db.$transaction(async tx=>{const payment=await tx.paymentTransaction.findUnique({where:{id},include:{booking:true}});if(!payment||payment.provider!=='SANDBOX'||payment.booking.status!=='CANCELLED')throw new BadRequestException('Only cancelled sandbox bookings can be refunded');if(payment.status==='REFUNDED')return payment;if(payment.status!=='SUCCEEDED')throw new BadRequestException('Payment is not refundable');const journal=await tx.ledgerTransaction.findUnique({where:{externalKey:`sandbox:${id}`},include:{entries:true}});if(!journal)throw new BadRequestException('Missing original journal');await tx.ledgerTransaction.create({data:{externalKey:`sandbox-refund:${id}`,description:'SANDBOX refund reversal — no funds moved',entries:{create:journal.entries.map(e=>({accountId:e.accountId,debitMinor:e.creditMinor,creditMinor:e.debitMinor}))}}});await tx.refund.create({data:{paymentId:id,amountMinor:payment.amountMinor,status:'SIMULATED',reason:d.reason}});await tx.auditLog.create({data:{actorId:r.authUser!.id,action:'SANDBOX_REFUND',entity:'PaymentTransaction',entityId:id,metadata:{reason:d.reason}}});return tx.paymentTransaction.update({where:{id},data:{status:'REFUNDED'}});},{isolationLevel:'Serializable'});}
 @Post('disputes/:id/resolve') async resolve(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:ResolveDto){return this.db.$transaction(async tx=>{const dispute=await tx.dispute.findUnique({where:{id},include:{booking:true}});if(!dispute||dispute.status!=='OPEN'||dispute.booking.status!=='DISPUTED')throw new BadRequestException('No active dispute');await tx.bookingHistory.create({data:{bookingId:dispute.bookingId,previous:'DISPUTED',next:d.status,actorId:r.authUser!.id}});await tx.booking.update({where:{id:dispute.bookingId},data:{status:d.status}});await tx.auditLog.create({data:{actorId:r.authUser!.id,action:'RESOLVE_DISPUTE',entity:'Dispute',entityId:id,metadata:{reason:d.reason,status:d.status}}});return tx.dispute.update({where:{id},data:{status:'RESOLVED'}});});}
}

