import { Controller,Get,Post,Patch,Delete,Body,Param,Req,Headers,UseGuards,BadRequestException,ForbiddenException } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { randomUUID } from 'crypto';
import { SessionGuard,AuthRequest } from '../common/session.guard';
import { WorkspaceService } from './workspace.service';
import { ProfileDto,PortfolioDto,ServiceDto,RequestDto,QuoteDto,ActionDto,MessageDto,ReviewDto,DeliverableDto,AgencyDto,MemberDto,SupportDto,AgencyServiceDto,AssignmentDto } from './dto';
@ApiTags('Workspace') @UseGuards(SessionGuard) @Controller('workspace') export class WorkspaceController {
 constructor(private service:WorkspaceService){} get db(){return this.service.db;}
 @Get() async overview(@Req() r:AuthRequest){const id=r.authUser!.id;const creator=await this.db.creator.findUnique({where:{userId:id},include:{portfolio:true,services:{include:{packages:true}}}});
  const bookings=await this.db.booking.findMany({where:{OR:[{customerId:id},{creator:{userId:id}},{agency:{members:{some:{userId:id,role:'AGENCY_ADMIN'}}}}]},include:{customer:{select:{name:true}},creator:{include:{user:{select:{name:true}}}},request:true},orderBy:{updatedAt:'desc'},take:100});
  const notifications=await this.db.notification.findMany({where:{userId:id},orderBy:{createdAt:'desc'},take:30});
  const agencies=await this.db.agencyMember.findMany({where:{userId:id},include:{agency:{include:{members:{include:{user:{select:{name:true}}}}}}}});
  const favorites=await this.db.favorite.findMany({where:{userId:id},include:{creator:{include:{user:{select:{name:true}}}}}});
  return {creator,bookings,notifications,agencies,favorites};
 }
 @Patch('profile') async profile(@Req() r:AuthRequest,@Body() d:ProfileDto){const c=await this.service.creator(r.authUser!.id);return this.db.creator.update({where:{id:c.id},data:d});}
 @Post('portfolio') async portfolio(@Req() r:AuthRequest,@Body() d:PortfolioDto){const c=await this.service.creator(r.authUser!.id);if(d.visibility==='PUBLIC'&&!d.clientConsent)throw new BadRequestException('Client permission required to publish');return this.db.portfolioProject.create({data:{...d,creatorId:c.id,slug:randomUUID(),publishedAt:d.visibility==='PUBLIC'?new Date():null}});}
 @Patch('portfolio/:id') async updatePortfolio(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:PortfolioDto){const c=await this.service.creator(r.authUser!.id);if(d.visibility==='PUBLIC'&&!d.clientConsent)throw new BadRequestException('Client permission required');const p=await this.db.portfolioProject.findFirst({where:{id,creatorId:c.id}});if(!p)throw new ForbiddenException();return this.db.portfolioProject.update({where:{id},data:{...d,publishedAt:d.visibility==='PUBLIC'?new Date():null}});}
 @Delete('portfolio/:id') async deletePortfolio(@Req() r:AuthRequest,@Param('id') id:string){const c=await this.service.creator(r.authUser!.id);return this.db.portfolioProject.deleteMany({where:{id,creatorId:c.id}});}
 @Post('services') async addService(@Req() r:AuthRequest,@Body() d:ServiceDto){const c=await this.service.creator(r.authUser!.id);const {priceMinor,revisions,durationDays,...service}=d;const category=await this.db.category.findFirst({where:{id:d.categoryId,active:true}});if(!category)throw new BadRequestException('Category unavailable');return this.db.service.create({data:{...service,creatorId:c.id,packages:{create:{title:d.title,priceMinor:BigInt(priceMinor),revisions,durationDays}}},include:{packages:true}});}
 @Patch('services/:id') async editService(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:ServiceDto){const c=await this.service.creator(r.authUser!.id);const s=await this.db.service.findFirst({where:{id,creatorId:c.id},include:{packages:true}});if(!s)throw new ForbiddenException();const {priceMinor,revisions,durationDays,...service}=d;return this.db.service.update({where:{id},data:{...service,packages:{update:{where:{id:s.packages[0].id},data:{title:d.title,priceMinor:BigInt(priceMinor),revisions,durationDays}}}}});}
 @Delete('services/:id') async archiveService(@Req() r:AuthRequest,@Param('id') id:string){const c=await this.service.creator(r.authUser!.id);return this.db.service.updateMany({where:{id,creatorId:c.id},data:{published:false}});}
 @Post('bookings') request(@Req() r:AuthRequest,@Body() d:RequestDto){return this.service.request(r.authUser!.id,d);}
 @Get('bookings/:id') booking(@Req() r:AuthRequest,@Param('id') id:string){return this.service.booking(id,r.authUser!.id);}
 @Post('bookings/:id/quote') quote(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:QuoteDto){return this.service.quote(id,r.authUser!.id,d);}
 @Post('bookings/:id/action') action(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:ActionDto){return this.service.transition(id,r.authUser!.id,d.status,d.reason);}
 @Post('bookings/:id/sandbox-payment') pay(@Req() r:AuthRequest,@Param('id') id:string,@Headers('idempotency-key') key:string){return this.service.sandboxPay(id,r.authUser!.id,key);}
 @Get('bookings/:id/messages') async messages(@Req() r:AuthRequest,@Param('id') id:string){const b=await this.service.booking(id,r.authUser!.id);await this.db.conversationParticipant.updateMany({where:{conversationId:b.conversation!.id,userId:r.authUser!.id},data:{lastReadAt:new Date()}});return this.db.message.findMany({where:{conversationId:b.conversation!.id},include:{sender:{select:{name:true}}},orderBy:{createdAt:'asc'},take:300});}
 @Post('bookings/:id/messages') async message(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:MessageDto){const b=await this.service.booking(id,r.authUser!.id);return this.db.$transaction(async tx=>{const m=await tx.message.create({data:{conversationId:b.conversation!.id,senderId:r.authUser!.id,text:d.text}});await this.service.notify(tx,b.customerId===r.authUser!.id?b.creator!.userId:b.customerId,'MESSAGE','New message',d.text.slice(0,150));return m;});}
 @Post('bookings/:id/deliverables') async deliver(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:DeliverableDto){const b=await this.service.booking(id,r.authUser!.id);if(b.customerId===r.authUser!.id||!['IN_PROGRESS','REVISION_REQUESTED'].includes(b.status))throw new ForbiddenException('Only provider on an active project can upload');return this.db.deliverable.create({data:{projectId:b.project!.id,filename:d.filename,storageKey:d.url,uploadedById:r.authUser!.id}});}
 @Post('bookings/:id/review') async review(@Req() r:AuthRequest,@Param('id') id:string,@Body() d:ReviewDto){return this.service.serial(async tx=>{const b=await this.service.booking(id,r.authUser!.id,tx);if(b.customerId!==r.authUser!.id||b.status!=='COMPLETED'||!b.creatorId)throw new ForbiddenException('Complete your booking before reviewing');if(b.review)throw new BadRequestException('Already reviewed');return tx.review.create({data:{bookingId:id,authorId:r.authUser!.id,creatorId:b.creatorId,...d}});});}
 @Post('favorites/:id') async favorite(@Req() r:AuthRequest,@Param('id') creatorId:string){if(!await this.db.creator.findFirst({where:{id:creatorId,published:true}}))throw new BadRequestException('Creator unavailable');return this.db.favorite.upsert({where:{userId_creatorId:{userId:r.authUser!.id,creatorId}},create:{userId:r.authUser!.id,creatorId},update:{}});}
 @Delete('favorites/:id') unfavorite(@Req() r:AuthRequest,@Param('id') creatorId:string){return this.db.favorite.deleteMany({where:{userId:r.authUser!.id,creatorId}});}
 @Patch('notifications/:id/read') read(@Req() r:AuthRequest,@Param('id') id:string){return this.db.notification.updateMany({where:{id,userId:r.authUser!.id},data:{readAt:new Date()}});}
 @Get('analytics') async analytics(@Req() r:AuthRequest){const c=await this.service.creator(r.authUser!.id);const bookings=await this.db.booking.findMany({where:{creatorId:c.id},select:{status:true,agreedAmountMinor:true,createdAt:true}});const payments=await this.db.paymentTransaction.findMany({where:{booking:{creatorId:c.id}},orderBy:{createdAt:'desc'}});return {profileViews:await this.db.analyticsEvent.count({where:{creatorId:c.id,eventType:'PROFILE_VIEW'}}),inquiries:bookings.length,completed:bookings.filter(b=>b.status==='COMPLETED').length,bookings,payments};}
 @Post('agencies') async agency(@Req() r:AuthRequest,@Body() d:AgencyDto){return this.db.$transaction(async tx=>{await tx.userRole.upsert({where:{userId_role:{userId:r.authUser!.id,role:'AGENCY_ADMIN'}},update:{},create:{userId:r.authUser!.id,role:'AGENCY_ADMIN'}});return tx.agency.create({data:{...d,members:{create:{userId:r.authUser!.id,role:'AGENCY_ADMIN'}}}});});}
 @Post('agencies/:id/members') async member(@Req() r:AuthRequest,@Param('id') agencyId:string,@Body() d:MemberDto){const admin=await this.db.agencyMember.findFirst({where:{agencyId,userId:r.authUser!.id,role:'AGENCY_ADMIN'}});if(!admin)throw new ForbiddenException();return this.db.$transaction(async tx=>{await tx.userRole.upsert({where:{userId_role:{userId:d.userId,role:d.role}},create:{userId:d.userId,role:d.role},update:{}});return tx.agencyMember.upsert({where:{agencyId_userId:{agencyId,userId:d.userId}},create:{agencyId,...d},update:{role:d.role}});});}
 @Get('agencies/:id') async agencyDetails(@Req() r:AuthRequest,@Param('id') id:string){const member=await this.db.agencyMember.findFirst({where:{agencyId:id,userId:r.authUser!.id}});if(!member)throw new ForbiddenException();const admin=member.role==='AGENCY_ADMIN';return {agency:await this.db.agency.findUnique({where:{id},include:{members:{include:{user:{select:{name:true,creator:{select:{id:true,username:true}}}}}},services:{include:{packages:true}}}}),bookings:await this.db.booking.findMany({where:{agencyId:id,...(!admin?{creator:{userId:r.authUser!.id}}:{})},include:{request:true,creator:{include:{user:{select:{name:true}}}},customer:{select:{name:true}}}})};}
 @Post('agencies/:id/services') async agencyService(@Req() r:AuthRequest,@Param('id') agencyId:string,@Body() d:AgencyServiceDto){if(!await this.db.agencyMember.findFirst({where:{agencyId,userId:r.authUser!.id,role:'AGENCY_ADMIN'}}))throw new ForbiddenException();const creator=await this.db.creator.findUnique({where:{id:d.creatorId}});if(!creator||!await this.db.agencyMember.findFirst({where:{agencyId,userId:creator.userId}}))throw new BadRequestException('Assign a creator from your agency');const {priceMinor,revisions,durationDays,...service}=d;return this.db.service.create({data:{...service,agencyId,packages:{create:{title:d.title,priceMinor:BigInt(priceMinor),revisions,durationDays}}}});}
 @Post('agencies/:id/bookings/:bookingId/assign') async assign(@Req() r:AuthRequest,@Param('id') agencyId:string,@Param('bookingId') bookingId:string,@Body() d:AssignmentDto){if(!await this.db.agencyMember.findFirst({where:{agencyId,userId:r.authUser!.id,role:'AGENCY_ADMIN'}}))throw new ForbiddenException();return this.service.serial(async tx=>{const b=await tx.booking.findUnique({where:{id:bookingId}});const creator=await tx.creator.findUnique({where:{id:d.creatorId}});if(!b||b.agencyId!==agencyId||b.status!=='REQUESTED'||!creator||!await tx.agencyMember.findFirst({where:{agencyId,userId:creator.userId}}))throw new BadRequestException('Only unquoted requests may be assigned to your team');await tx.auditLog.create({data:{actorId:r.authUser!.id,action:'ASSIGN_AGENCY_BOOKING',entity:'Booking',entityId:bookingId,metadata:{creatorId:creator.id}}});return tx.booking.update({where:{id:bookingId},data:{creatorId:creator.id}});});}
 @Post('support') support(@Req() r:AuthRequest,@Body() d:SupportDto){return this.db.supportTicket.create({data:{openedById:r.authUser!.id,...d}});}
 @Get('export') async export(@Req() r:AuthRequest){const id=r.authUser!.id;return {account:await this.db.user.findUnique({where:{id},select:{id:true,name:true,phone:true,createdAt:true}}),workspace:await this.overview(r),messages:await this.db.message.findMany({where:{senderId:id}})};}
 @Delete('account') async deleteAccount(@Req() r:AuthRequest){const id=r.authUser!.id;const active=await this.db.booking.count({where:{OR:[{customerId:id},{creator:{userId:id}},{agency:{members:{some:{userId:id,role:'AGENCY_ADMIN'}}}}],status:{notIn:['COMPLETED','CANCELLED','REJECTED','EXPIRED']}}});if(active)throw new BadRequestException('Resolve active bookings before deleting your account');return this.db.$transaction(async tx=>{await tx.session.updateMany({where:{userId:id},data:{revokedAt:new Date()}});await tx.creator.updateMany({where:{userId:id},data:{published:false}});await tx.user.update({where:{id},data:{deletedAt:new Date(),name:'Deleted user',email:`deleted-${id}@invalid.local`,passwordHash:null,phone:null,avatarUrl:null}});return {ok:true};});}
}
