'use client';
import {useEffect,useState,useCallback} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {ApiForm} from './workspace';
import MediaUpload from './media-upload';
type Booking={id:string;customerId:string;status:string;agreedAmountMinor:string|null;creator:{userId:string;user:{name:string}};customer:{name:string};request:{title:string;details:string};quotation:{description:string;expiresAt:string}|null;project:{deliverables:{id:string;filename:string;storageKey:string}[]};paymentTransactions:{id:string;provider:string;status:string;amountMinor:string}[];review:{rating:number;text:string}|null;history:{id:string;next:string;createdAt:string}[]};
type Message={id:string;sender:{name:string};text:string;createdAt:string};
export default function BookingDetail({id}:{id:string}){
 const [b,setBooking]=useState<Booking|null>(null),[me,setMe]=useState<{id:string}|null>(null),[messages,setMessages]=useState<Message[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{try{const [booking,user,msg]=await Promise.all([api<Booking>(`/workspace/bookings/${id}`),api<{id:string}>('/auth/me'),api<Message[]>(`/workspace/bookings/${id}/messages`)]);setBooking(booking);setMe(user);setMessages(msg);}catch(e){setError(e instanceof Error?e.message:'Failed to load project');}},[id]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{void refresh();},15000);return()=>clearInterval(timer);},[refresh]);
 async function action(status:string){setBusy(true);setError('');try{const reason=status==='DISPUTED'?window.prompt('Describe the dispute'):undefined;if(status==='DISPUTED'&&!reason)return;await api(`/workspace/bookings/${id}/action`,{method:'POST',body:JSON.stringify({status,...(reason?{reason}:{})})});await refresh();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(false);}}
 if(!b||!me)return <main className="max-w-6xl mx-auto p-10">{error||'Loading project…'}<Link className="block text-blue-300 mt-5" href="/dashboard/bookings">Back to bookings</Link></main>;
 const customer=b.customerId===me.id;const actions:string[]=[];
 if(customer){if(b.status==='QUOTED')actions.push('AWAITING_PAYMENT');if(b.status==='DELIVERED')actions.push('COMPLETED','REVISION_REQUESTED');if(['REQUESTED','QUOTED','AWAITING_PAYMENT','CONFIRMED','IN_PROGRESS'].includes(b.status))actions.push('CANCELLED');if(['CONFIRMED','IN_PROGRESS','DELIVERED','COMPLETED'].includes(b.status))actions.push('DISPUTED');}
 else {if(b.status==='REQUESTED')actions.push('REJECTED');if(['CONFIRMED','REVISION_REQUESTED'].includes(b.status))actions.push('IN_PROGRESS');if(b.status==='IN_PROGRESS')actions.push('DELIVERED');}
 const label:Record<string,string>={AWAITING_PAYMENT:'Accept quotation',COMPLETED:'Approve completion',REVISION_REQUESTED:'Request revision',CANCELLED:'Cancel booking',DISPUTED:'Open dispute',REJECTED:'Reject request',IN_PROGRESS:'Start work',DELIVERED:'Submit for approval'};
 return <main className="max-w-6xl mx-auto px-5 py-10"><Link href="/dashboard/bookings" className="text-blue-300 text-sm">← All bookings</Link><div className="my-7"><p className="text-xs text-blue-400">{b.status.replace(/_/g,' ')}</p><h1 className="text-3xl font-bold mt-3">{b.request.title}</h1><p className="muted mt-3">{b.customer.name} × {b.creator.user.name}</p></div>{error&&<p role="alert" className="text-red-300 mb-5">{error}</p>}
 <div className="grid lg:grid-cols-[1fr_340px] gap-6"><div className="space-y-6"><div className="panel p-7"><h2 className="font-bold text-lg">Project requirements</h2><p className="muted whitespace-pre-wrap mt-4">{b.request.details}</p></div>
 {b.quotation&&<div className="panel p-7"><h2 className="font-bold text-lg">Quotation · LKR {(Number(b.agreedAmountMinor)/100).toLocaleString('en-LK')}</h2><p className="muted mt-4 whitespace-pre-wrap">{b.quotation.description}</p><p className="muted text-xs mt-4">Expires {new Date(b.quotation.expiresAt).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</p></div>}
 {!customer&&b.status==='REQUESTED'&&<div className="panel p-7"><h2 className="font-bold mb-5">Send quotation</h2><ApiForm path={`/workspace/bookings/${id}/quote`} onSuccess={refresh} fields={[{name:'amountMinor',label:'Quotation total (LKR)',type:'currency',required:true},{name:'description',label:'Scope, deliverables and conditions',type:'textarea',required:true},{name:'expiresAt',label:'Expiry date and time',type:'datetime-local',required:true}]}/></div>}
 <div className="panel p-7"><h2 className="font-bold mb-5">Deliverables</h2>{b.project.deliverables.length?b.project.deliverables.map(d=><button key={d.id} className="block text-blue-300 py-3" onClick={async()=>{try{const url=d.storageKey.startsWith('object:')?(await api<{url:string}>(`/media/${d.storageKey.slice(7)}/private`)).url:d.storageKey;window.open(url,'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:'Download failed');}}}>{d.filename} ↗</button>):<p className="muted mb-5">No deliverables yet.</p>}{!customer&&['IN_PROGRESS','REVISION_REQUESTED'].includes(b.status)&&<div className="space-y-5"><MediaUpload bookingId={id} onDone={()=>{void refresh();}}/><ApiForm path={`/workspace/bookings/${id}/deliverables`} onSuccess={refresh} fields={[{name:'filename',label:'Deliverable title',required:true},{name:'url',label:'HTTPS delivery link (use restricted sharing)',type:'url',required:true}]} label="Add deliverable link"/></div>}</div>
 <div className="panel p-7"><h2 className="font-bold mb-5">Private project conversation</h2><div className="space-y-4 mb-6 max-h-96 overflow-y-auto">{messages.length?messages.map(m=><div className="bg-white/5 p-4 rounded-xl" key={m.id}><p className="text-xs text-blue-300">{m.sender.name} · {new Date(m.createdAt).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</p><p className="mt-2 whitespace-pre-wrap text-sm">{m.text}</p></div>):<p className="muted">Introduce your project here.</p>}</div><ApiForm path={`/workspace/bookings/${id}/messages`} onSuccess={refresh} fields={[{name:'text',label:'Message',type:'textarea',required:true}]} label="Send message"/></div>
 {customer&&b.status==='COMPLETED'&&!b.review&&<div className="panel p-7"><h2 className="font-bold mb-5">Review your completed booking</h2><ApiForm path={`/workspace/bookings/${id}/review`} onSuccess={refresh} fields={[{name:'rating',label:'Rating (1–5)',type:'number',value:5,required:true},{name:'text',label:'Your experience',type:'textarea',required:true}]} label="Submit verified booking review"/></div>}{b.review&&<div className="panel p-7">{'★'.repeat(b.review.rating)}<p className="muted mt-3">{b.review.text}</p></div>}</div>
 <aside className="space-y-5"><div className="panel p-6"><h2 className="font-bold mb-5">Project actions</h2><div className="grid gap-3">{actions.length?actions.map(a=><button disabled={busy} key={a} className="btn btn-outline text-sm" onClick={()=>action(a)}>{label[a]}</button>):<p className="muted text-sm">Waiting for the next project step.</p>}</div>
 {customer&&b.status==='AWAITING_PAYMENT'&&<div className="mt-6 border-t border-white/10 pt-5"><p className="text-amber-300 text-sm mb-4">Test checkout only. No real money is collected or paid out.</p><button disabled={busy} className="btn btn-primary w-full" onClick={async()=>{setBusy(true);try{await api(`/workspace/bookings/${id}/sandbox-payment`,{method:'POST',headers:{'Idempotency-Key':`booking_${id}`}});await refresh();}catch(e){setError(e instanceof Error?e.message:'Checkout failed');}finally{setBusy(false);}}}>Simulate sandbox payment</button></div>}</div>
 <div className="panel p-6"><h2 className="font-bold">Payment history</h2>{b.paymentTransactions.map(p=><p key={p.id} className="text-sm text-amber-300 mt-4">{p.provider} · {p.status} · LKR {Number(p.amountMinor)/100}</p>)}</div><div className="panel p-6"><h2 className="font-bold">Project timeline</h2>{b.history.map(h=><p key={h.id} className="text-sm muted mt-4">{h.next.replace(/_/g,' ')}<span className="block text-xs mt-1">{new Date(h.createdAt).toLocaleString('en-LK',{timeZone:'Asia/Colombo'})}</span></p>)}</div></aside></div></main>;
}
